g.books = [
    ["Pride and Prejudice","https://www.gutenberg.org/cache/epub/1342/pg1342.txt"],
    ["Alice's Adventures in Wonderland","https://www.gutenberg.org/cache/epub/11/pg11.txt"],
    ["Adventures of Huckleberry Finn","https://www.gutenberg.org/cache/epub/76/pg76.txt"],
    ["The Importance of Being Earnest","https://www.gutenberg.org/cache/epub/844/pg844.txt"],
    ["The Adventures of Tom Sawyer","https://www.gutenberg.org/cache/epub/74/pg74.txt"],
    ["A Doll's House","https://www.gutenberg.org/cache/epub/2542/pg2542.txt"],
    ["Metamorphosis","https://www.gutenberg.org/cache/epub/5200/pg5200.txt"],
    ["The Yellow Wallpaper","https://www.gutenberg.org/cache/epub/1952/pg1952.txt"],
    ["A Tale of Two Cities","https://www.gutenberg.org/cache/epub/98/pg98.txt"],
    ["Ulysses","https://www.gutenberg.org/cache/epub/4300/pg4300.txt"],
    ["The Kama Sutra of Vatsyayana","https://www.gutenberg.org/cache/epub/27827/pg27827.txt"],
    ["The Picture of Dorian Gray","https://www.gutenberg.org/cache/epub/174/pg174.txt"],
    ["Frankenstein; Or, The Modern Prometheus","https://www.gutenberg.org/cache/epub/84/pg84.txt"],
    ["Grimms' Fairy Tales","https://www.gutenberg.org/cache/epub/2591/pg2591.txt"],
    ["The Prince","https://www.gutenberg.org/cache/epub/1232/pg1232.txt"],
    ["The Adventures of Sherlock Holmes","https://www.gutenberg.org/cache/epub/1661/pg1661.txt"],
    ["A Modest Proposal","https://www.gutenberg.org/cache/epub/1080/pg1080.txt"],
    ["Moby Dick; Or, The Whale","https://www.gutenberg.org/cache/epub/2701/pg2701.txt"],
    ["Great Expectations","https://www.gutenberg.org/cache/epub/1400/pg1400.txt"],
    ["Narrative of the Life of Frederick Douglass, an American Slave","https://www.gutenberg.org/cache/epub/23/pg23.txt"],
    ["Leaves of Grass","https://www.gutenberg.org/cache/epub/1322/pg1322.txt"],
    ["Dracula","https://www.gutenberg.org/cache/epub/345/pg345.txt"],
    ["Les Miserables","https://www.gutenberg.org/cache/epub/135/pg135.txt"],
    ["Emma","https://www.gutenberg.org/cache/epub/158/pg158.txt"],
    ["Steam, Its Generation and Use","https://www.gutenberg.org/cache/epub/22657/pg22657.txt"],
    ["Beowulf","https://www.gutenberg.org/cache/epub/16328/pg16328.txt"],
    ["Dubliners","https://www.gutenberg.org/cache/epub/2814/pg2814.txt"],
    ["Jane Eyre: An Autobiography","https://www.gutenberg.org/cache/epub/1260/pg1260.txt"],
    ["The Romance of Lust","https://www.gutenberg.org/cache/epub/30254/pg30254.txt"],
    ["The Divine Comedy","https://www.gutenberg.org/cache/epub/8800/pg8800.txt"],
]
