g.books = [
    ["Pride and Prejudice","http://d2yzl2mysmkr1m.cloudfront.net/gbbooks/pg1342.txt"],
    ["Alice's Adventures in Wonderland","http://d2yzl2mysmkr1m.cloudfront.net/gbbooks/pg11.txt"],
    ["Adventures of Huckleberry Finn","http://d2yzl2mysmkr1m.cloudfront.net/gbbooks/pg76.txt"],
    ["The Importance of Being Earnest","http://d2yzl2mysmkr1m.cloudfront.net/gbbooks/pg844.txt"],
    ["The Adventures of Tom Sawyer","http://d2yzl2mysmkr1m.cloudfront.net/gbbooks/pg74.txt"],
    ["A Doll's House","http://d2yzl2mysmkr1m.cloudfront.net/gbbooks/pg2542.txt"],
    ["Metamorphosis","http://d2yzl2mysmkr1m.cloudfront.net/gbbooks/pg5200.txt"],
    ["The Yellow Wallpaper","http://d2yzl2mysmkr1m.cloudfront.net/gbbooks/pg1952.txt"],
    ["A Tale of Two Cities","http://d2yzl2mysmkr1m.cloudfront.net/gbbooks/pg98.txt"],
    ["Ulysses","http://d2yzl2mysmkr1m.cloudfront.net/gbbooks/pg4300.txt"],
    ["The Kama Sutra of Vatsyayana","http://d2yzl2mysmkr1m.cloudfront.net/gbbooks/pg27827.txt"],
    ["The Picture of Dorian Gray","http://d2yzl2mysmkr1m.cloudfront.net/gbbooks/pg174.txt"],
    ["Frankenstein; Or, The Modern Prometheus","http://d2yzl2mysmkr1m.cloudfront.net/gbbooks/pg84.txt"],
    ["Grimms' Fairy Tales","http://d2yzl2mysmkr1m.cloudfront.net/gbbooks/pg2591.txt"],
    ["The Prince","http://d2yzl2mysmkr1m.cloudfront.net/gbbooks/pg1232.txt"],
    ["The Adventures of Sherlock Holmes","http://d2yzl2mysmkr1m.cloudfront.net/gbbooks/pg1661.txt"],
    ["A Modest Proposal","http://d2yzl2mysmkr1m.cloudfront.net/gbbooks/pg1080.txt"],
    ["Moby Dick; Or, The Whale","http://d2yzl2mysmkr1m.cloudfront.net/gbbooks/pg2701.txt"],
    ["Great Expectations","http://d2yzl2mysmkr1m.cloudfront.net/gbbooks/pg1400.txt"],
    ["Narrative of the Life of Frederick Douglass, an American Slave","http://d2yzl2mysmkr1m.cloudfront.net/gbbooks/pg23.txt"],
    ["Leaves of Grass","http://d2yzl2mysmkr1m.cloudfront.net/gbbooks/pg1322.txt"],
    ["Dracula","http://d2yzl2mysmkr1m.cloudfront.net/gbbooks/pg345.txt"],
    ["Les Miserables","http://d2yzl2mysmkr1m.cloudfront.net/gbbooks/pg135.txt"],
    ["Emma","http://d2yzl2mysmkr1m.cloudfront.net/gbbooks/pg158.txt"],
    ["Steam, Its Generation and Use","http://d2yzl2mysmkr1m.cloudfront.net/gbbooks/pg22657.txt"],
    ["Beowulf","http://d2yzl2mysmkr1m.cloudfront.net/gbbooks/pg16328.txt"],
    ["Dubliners","http://d2yzl2mysmkr1m.cloudfront.net/gbbooks/pg2814.txt"],
    ["Jane Eyre: An Autobiography","http://d2yzl2mysmkr1m.cloudfront.net/gbbooks/pg1260.txt"],
    ["The Romance of Lust","http://d2yzl2mysmkr1m.cloudfront.net/gbbooks/pg30254.txt"],
    ["The Divine Comedy","http://d2yzl2mysmkr1m.cloudfront.net/gbbooks/pg8800.txt"],
]
