g.books = [
    ["Pride and Prejudice","http://ticc.net/books/pg1342.txt"],
    ["Alice's Adventures in Wonderland","http://ticc.net/books/pg11.txt"],
    ["Adventures of Huckleberry Finn","http://ticc.net/books/pg76.txt"],
    ["The Importance of Being Earnest","http://ticc.net/books/pg844.txt"],
    ["The Adventures of Tom Sawyer","http://ticc.net/books/pg74.txt"],
    ["A Doll's House","http://ticc.net/books/pg2542.txt"],
    ["Metamorphosis","http://ticc.net/books/pg5200.txt"],
    ["The Yellow Wallpaper","http://ticc.net/books/pg1952.txt"],
    ["A Tale of Two Cities","http://ticc.net/books/pg98.txt"],
    ["Ulysses","http://ticc.net/books/pg4300.txt"],
    ["The Kama Sutra of Vatsyayana","http://ticc.net/books/pg27827.txt"],
    ["The Picture of Dorian Gray","http://ticc.net/books/pg174.txt"],
    ["Frankenstein; Or, The Modern Prometheus","http://ticc.net/books/pg84.txt"],
    ["Grimms' Fairy Tales","http://ticc.net/books/pg2591.txt"],
    ["The Prince","http://ticc.net/books/pg1232.txt"],
    ["The Adventures of Sherlock Holmes","http://ticc.net/books/pg1661.txt"],
    ["A Modest Proposal","http://ticc.net/books/pg1080.txt"],
    ["Moby Dick; Or, The Whale","http://ticc.net/books/pg2701.txt"],
    ["Great Expectations","http://ticc.net/books/pg1400.txt"],
    ["Narrative of the Life of Frederick Douglass, an American Slave","http://ticc.net/books/pg23.txt"],
    ["Leaves of Grass","http://ticc.net/books/pg1322.txt"],
    ["Dracula","http://ticc.net/books/pg345.txt"],
    ["Les Miserables","http://ticc.net/books/pg135.txt"],
    ["Emma","http://ticc.net/books/pg158.txt"],
    ["Steam, Its Generation and Use","http://ticc.net/books/pg22657.txt"],
    ["Beowulf","http://ticc.net/books/pg16328.txt"],
    ["Dubliners","http://ticc.net/books/pg2814.txt"],
    ["Jane Eyre: An Autobiography","http://ticc.net/books/pg1260.txt"],
    ["The Romance of Lust","http://ticc.net/books/pg30254.txt"],
    ["The Divine Comedy","http://ticc.net/books/pg8800.txt"],
]
